//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.MicrowunderlandInterfaces
{
    [Serializable]
    public class AssigneTravelPlanResponse : Message
    {
        public const string k_RosMessageName = "microwunderland_interfaces/AssigneTravelPlan";
        public override string RosMessageName => k_RosMessageName;

        public sbyte status;
        //  0=travel plan assigned; 1=not assigned, vehicle not found; 2=not assigned, plan not found

        public AssigneTravelPlanResponse()
        {
            this.status = 0;
        }

        public AssigneTravelPlanResponse(sbyte status)
        {
            this.status = status;
        }

        public static AssigneTravelPlanResponse Deserialize(MessageDeserializer deserializer) => new AssigneTravelPlanResponse(deserializer);

        private AssigneTravelPlanResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.status);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.status);
        }

        public override string ToString()
        {
            return "AssigneTravelPlanResponse: " +
            "\nstatus: " + status.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
