//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.MicrowunderlandInterfaces
{
    [Serializable]
    public class ExportImageResponse : Message
    {
        public const string k_RosMessageName = "microwunderland_interfaces/ExportImage";
        public override string RosMessageName => k_RosMessageName;

        public byte status;
        //  status of service call equals 1 if r

        public ExportImageResponse()
        {
            this.status = 0;
        }

        public ExportImageResponse(byte status)
        {
            this.status = status;
        }

        public static ExportImageResponse Deserialize(MessageDeserializer deserializer) => new ExportImageResponse(deserializer);

        private ExportImageResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.status);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.status);
        }

        public override string ToString()
        {
            return "ExportImageResponse: " +
            "\nstatus: " + status.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
