//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.MicrowunderlandInterfaces
{
    [Serializable]
    public class GetUInt32Response : Message
    {
        public const string k_RosMessageName = "microwunderland_interfaces/GetUInt32";
        public override string RosMessageName => k_RosMessageName;

        public uint value;
        //  return value
        public byte status;
        //  status code

        public GetUInt32Response()
        {
            this.value = 0;
            this.status = 0;
        }

        public GetUInt32Response(uint value, byte status)
        {
            this.value = value;
            this.status = status;
        }

        public static GetUInt32Response Deserialize(MessageDeserializer deserializer) => new GetUInt32Response(deserializer);

        private GetUInt32Response(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.value);
            deserializer.Read(out this.status);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.value);
            serializer.Write(this.status);
        }

        public override string ToString()
        {
            return "GetUInt32Response: " +
            "\nvalue: " + value.ToString() +
            "\nstatus: " + status.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
