//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.MicrowunderlandInterfaces
{
    [Serializable]
    public class SetStringRequest : Message
    {
        public const string k_RosMessageName = "microwunderland_interfaces/SetString";
        public override string RosMessageName => k_RosMessageName;

        //  Service interface with a string parameter
        public string value;
        //  string param

        public SetStringRequest()
        {
            this.value = "";
        }

        public SetStringRequest(string value)
        {
            this.value = value;
        }

        public static SetStringRequest Deserialize(MessageDeserializer deserializer) => new SetStringRequest(deserializer);

        private SetStringRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.value);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.value);
        }

        public override string ToString()
        {
            return "SetStringRequest: " +
            "\nvalue: " + value.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
