//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.MicrowunderlandInterfaces
{
    [Serializable]
    public class SetStringKeyValueResponse : Message
    {
        public const string k_RosMessageName = "microwunderland_interfaces/SetStringKeyValue";
        public override string RosMessageName => k_RosMessageName;

        public byte status;
        //  status code; Equals zero if all went well one if key was not found

        public SetStringKeyValueResponse()
        {
            this.status = 0;
        }

        public SetStringKeyValueResponse(byte status)
        {
            this.status = status;
        }

        public static SetStringKeyValueResponse Deserialize(MessageDeserializer deserializer) => new SetStringKeyValueResponse(deserializer);

        private SetStringKeyValueResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.status);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.status);
        }

        public override string ToString()
        {
            return "SetStringKeyValueResponse: " +
            "\nstatus: " + status.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
