//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.MicrowunderlandInterfaces
{
    [Serializable]
    public class SetStringResponse : Message
    {
        public const string k_RosMessageName = "microwunderland_interfaces/SetString";
        public override string RosMessageName => k_RosMessageName;

        public byte status;
        //  status code indicating the result of the service call

        public SetStringResponse()
        {
            this.status = 0;
        }

        public SetStringResponse(byte status)
        {
            this.status = status;
        }

        public static SetStringResponse Deserialize(MessageDeserializer deserializer) => new SetStringResponse(deserializer);

        private SetStringResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.status);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.status);
        }

        public override string ToString()
        {
            return "SetStringResponse: " +
            "\nstatus: " + status.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
