//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.MicrowunderlandInterfaces
{
    [Serializable]
    public class SetStateRequest : Message
    {
        public const string k_RosMessageName = "microwunderland_interfaces/SetState";
        public override string RosMessageName => k_RosMessageName;

        //  sets the the active state of a switch
        public string switch_name;
        //  name of the switch that shall be controlled
        public string state_name;
        //  name of the desired state

        public SetStateRequest()
        {
            this.switch_name = "";
            this.state_name = "";
        }

        public SetStateRequest(string switch_name, string state_name)
        {
            this.switch_name = switch_name;
            this.state_name = state_name;
        }

        public static SetStateRequest Deserialize(MessageDeserializer deserializer) => new SetStateRequest(deserializer);

        private SetStateRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.switch_name);
            deserializer.Read(out this.state_name);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.switch_name);
            serializer.Write(this.state_name);
        }

        public override string ToString()
        {
            return "SetStateRequest: " +
            "\nswitch_name: " + switch_name.ToString() +
            "\nstate_name: " + state_name.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
