//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.MicrowunderlandInterfaces
{
    [Serializable]
    public class SetUint32KeyValueRequest : Message
    {
        public const string k_RosMessageName = "microwunderland_interfaces/SetUint32KeyValue";
        public override string RosMessageName => k_RosMessageName;

        //  sets a uint32
        public string key;
        //  key value 
        public uint value;
        //  value to sets

        public SetUint32KeyValueRequest()
        {
            this.key = "";
            this.value = 0;
        }

        public SetUint32KeyValueRequest(string key, uint value)
        {
            this.key = key;
            this.value = value;
        }

        public static SetUint32KeyValueRequest Deserialize(MessageDeserializer deserializer) => new SetUint32KeyValueRequest(deserializer);

        private SetUint32KeyValueRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.key);
            deserializer.Read(out this.value);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.key);
            serializer.Write(this.value);
        }

        public override string ToString()
        {
            return "SetUint32KeyValueRequest: " +
            "\nkey: " + key.ToString() +
            "\nvalue: " + value.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
