//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.MicrowunderlandInterfaces
{
    [Serializable]
    public class StringArrayRequest : Message
    {
        public const string k_RosMessageName = "microwunderland_interfaces/StringArray";
        public override string RosMessageName => k_RosMessageName;

        //  Service that accepts a list of string values and returns a status
        public string[] strings;
        //  list of strings

        public StringArrayRequest()
        {
            this.strings = new string[0];
        }

        public StringArrayRequest(string[] strings)
        {
            this.strings = strings;
        }

        public static StringArrayRequest Deserialize(MessageDeserializer deserializer) => new StringArrayRequest(deserializer);

        private StringArrayRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.strings, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.strings);
            serializer.Write(this.strings);
        }

        public override string ToString()
        {
            return "StringArrayRequest: " +
            "\nstrings: " + System.String.Join(", ", strings.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
