//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.ServoController
{
    [Serializable]
    public class GetAvailableStatesResponse : Message
    {
        public const string k_RosMessageName = "servo_controller/GetAvailableStates";
        public override string RosMessageName => k_RosMessageName;

        //  output 
        public StringUint16PairMsg[] states;
        //  list of available states
        public byte status;
        //  status code; Equals zero if all went well

        public GetAvailableStatesResponse()
        {
            this.states = new StringUint16PairMsg[0];
            this.status = 0;
        }

        public GetAvailableStatesResponse(StringUint16PairMsg[] states, byte status)
        {
            this.states = states;
            this.status = status;
        }

        public static GetAvailableStatesResponse Deserialize(MessageDeserializer deserializer) => new GetAvailableStatesResponse(deserializer);

        private GetAvailableStatesResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.states, StringUint16PairMsg.Deserialize, deserializer.ReadLength());
            deserializer.Read(out this.status);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.states);
            serializer.Write(this.states);
            serializer.Write(this.status);
        }

        public override string ToString()
        {
            return "GetAvailableStatesResponse: " +
            "\nstates: " + System.String.Join(", ", states.ToList()) +
            "\nstatus: " + status.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
