//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.ServoController
{
    [Serializable]
    public class GetAvailableStatesRequest : Message
    {
        public const string k_RosMessageName = "servo_controller/GetAvailableStates";
        public override string RosMessageName => k_RosMessageName;

        //  returns all available states of a switch; one states consists out of a string (name) and int (position)
        public string switch_name;
        //  name of the switch that shall be controlled

        public GetAvailableStatesRequest()
        {
            this.switch_name = "";
        }

        public GetAvailableStatesRequest(string switch_name)
        {
            this.switch_name = switch_name;
        }

        public static GetAvailableStatesRequest Deserialize(MessageDeserializer deserializer) => new GetAvailableStatesRequest(deserializer);

        private GetAvailableStatesRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.switch_name);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.switch_name);
        }

        public override string ToString()
        {
            return "GetAvailableStatesRequest: " +
            "\nswitch_name: " + switch_name.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
