//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.ServoController
{
    [Serializable]
    public class GetCurrentStateResponse : Message
    {
        public const string k_RosMessageName = "servo_controller/GetCurrentState";
        public override string RosMessageName => k_RosMessageName;

        public string state_name;
        //  name of the active state
        public byte status;
        //  status code; Equals zero if all went well

        public GetCurrentStateResponse()
        {
            this.state_name = "";
            this.status = 0;
        }

        public GetCurrentStateResponse(string state_name, byte status)
        {
            this.state_name = state_name;
            this.status = status;
        }

        public static GetCurrentStateResponse Deserialize(MessageDeserializer deserializer) => new GetCurrentStateResponse(deserializer);

        private GetCurrentStateResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.state_name);
            deserializer.Read(out this.status);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.state_name);
            serializer.Write(this.status);
        }

        public override string ToString()
        {
            return "GetCurrentStateResponse: " +
            "\nstate_name: " + state_name.ToString() +
            "\nstatus: " + status.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
