//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.ServoController
{
    [Serializable]
    public class SetStateResponse : Message
    {
        public const string k_RosMessageName = "servo_controller/SetState";
        public override string RosMessageName => k_RosMessageName;

        public byte status;
        //  status code; Equals zero if all went well

        public SetStateResponse()
        {
            this.status = 0;
        }

        public SetStateResponse(byte status)
        {
            this.status = status;
        }

        public static SetStateResponse Deserialize(MessageDeserializer deserializer) => new SetStateResponse(deserializer);

        private SetStateResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.status);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.status);
        }

        public override string ToString()
        {
            return "SetStateResponse: " +
            "\nstatus: " + status.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
