//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.MicrowunderlandInterfaces
{
    [Serializable]
    public class BoundingBoxMsg : Message
    {
        public const string k_RosMessageName = "microwunderland_interfaces/BoundingBox";
        public override string RosMessageName => k_RosMessageName;

        //  BoundingBox msg
        public Vector2DMsg pos1;
        public Vector2DMsg pos2;
        public string label;

        public BoundingBoxMsg()
        {
            this.pos1 = new Vector2DMsg();
            this.pos2 = new Vector2DMsg();
            this.label = "";
        }

        public BoundingBoxMsg(Vector2DMsg pos1, Vector2DMsg pos2, string label)
        {
            this.pos1 = pos1;
            this.pos2 = pos2;
            this.label = label;
        }

        public static BoundingBoxMsg Deserialize(MessageDeserializer deserializer) => new BoundingBoxMsg(deserializer);

        private BoundingBoxMsg(MessageDeserializer deserializer)
        {
            this.pos1 = Vector2DMsg.Deserialize(deserializer);
            this.pos2 = Vector2DMsg.Deserialize(deserializer);
            deserializer.Read(out this.label);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.pos1);
            serializer.Write(this.pos2);
            serializer.Write(this.label);
        }

        public override string ToString()
        {
            return "BoundingBoxMsg: " +
            "\npos1: " + pos1.ToString() +
            "\npos2: " + pos2.ToString() +
            "\nlabel: " + label.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
