//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.MicrowunderlandInterfaces
{
    [Serializable]
    public class BoundingBoxListMsg : Message
    {
        public const string k_RosMessageName = "microwunderland_interfaces/BoundingBoxList";
        public override string RosMessageName => k_RosMessageName;

        //  Array of bounding boxes
        public BoundingBoxMsg[] boxes;

        public BoundingBoxListMsg()
        {
            this.boxes = new BoundingBoxMsg[0];
        }

        public BoundingBoxListMsg(BoundingBoxMsg[] boxes)
        {
            this.boxes = boxes;
        }

        public static BoundingBoxListMsg Deserialize(MessageDeserializer deserializer) => new BoundingBoxListMsg(deserializer);

        private BoundingBoxListMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.boxes, BoundingBoxMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.boxes);
            serializer.Write(this.boxes);
        }

        public override string ToString()
        {
            return "BoundingBoxListMsg: " +
            "\nboxes: " + System.String.Join(", ", boxes.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
