//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.MicrowunderlandInterfaces
{
    [Serializable]
    public class BoundingBoxMsg : Message
    {
        public const string k_RosMessageName = "microwunderland_interfaces/BoundingBox";
        public override string RosMessageName => k_RosMessageName;

        //  used to send the resoults from a object detector that outputs bounding boxes
        public Vector2DMsg vec_a;
        //  if minMax formate vec_a = min; if centerSize format vec_a = center
        public Vector2DMsg vec_b;
        //  if minMax formate vec_a = max; if centerSize format vec_a = size
        public byte format;
        //  0 equlas minMax; 1 equlas centerSize
        public string label_name;
        //  name of the detected object

        public BoundingBoxMsg()
        {
            this.vec_a = new Vector2DMsg();
            this.vec_b = new Vector2DMsg();
            this.format = 0;
            this.label_name = "";
        }

        public BoundingBoxMsg(Vector2DMsg vec_a, Vector2DMsg vec_b, byte format, string label_name)
        {
            this.vec_a = vec_a;
            this.vec_b = vec_b;
            this.format = format;
            this.label_name = label_name;
        }

        public static BoundingBoxMsg Deserialize(MessageDeserializer deserializer) => new BoundingBoxMsg(deserializer);

        private BoundingBoxMsg(MessageDeserializer deserializer)
        {
            this.vec_a = Vector2DMsg.Deserialize(deserializer);
            this.vec_b = Vector2DMsg.Deserialize(deserializer);
            deserializer.Read(out this.format);
            deserializer.Read(out this.label_name);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.vec_a);
            serializer.Write(this.vec_b);
            serializer.Write(this.format);
            serializer.Write(this.label_name);
        }

        public override string ToString()
        {
            return "BoundingBoxMsg: " +
            "\nvec_a: " + vec_a.ToString() +
            "\nvec_b: " + vec_b.ToString() +
            "\nformat: " + format.ToString() +
            "\nlabel_name: " + label_name.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
