//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.MicrowunderlandInterfaces
{
    [Serializable]
    public class LabeledImageMsg : Message
    {
        public const string k_RosMessageName = "microwunderland_interfaces/LabeledImage";
        public override string RosMessageName => k_RosMessageName;

        public Sensor.CompressedImageMsg image;
        //  analysed compressed/image 
        public BoundingBoxMsg[] bounding_boxes;
        //  detected bounding boxes

        public LabeledImageMsg()
        {
            this.image = new Sensor.CompressedImageMsg();
            this.bounding_boxes = new BoundingBoxMsg[0];
        }

        public LabeledImageMsg(Sensor.CompressedImageMsg image, BoundingBoxMsg[] bounding_boxes)
        {
            this.image = image;
            this.bounding_boxes = bounding_boxes;
        }

        public static LabeledImageMsg Deserialize(MessageDeserializer deserializer) => new LabeledImageMsg(deserializer);

        private LabeledImageMsg(MessageDeserializer deserializer)
        {
            this.image = Sensor.CompressedImageMsg.Deserialize(deserializer);
            deserializer.Read(out this.bounding_boxes, BoundingBoxMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.image);
            serializer.WriteLength(this.bounding_boxes);
            serializer.Write(this.bounding_boxes);
        }

        public override string ToString()
        {
            return "LabeledImageMsg: " +
            "\nimage: " + image.ToString() +
            "\nbounding_boxes: " + System.String.Join(", ", bounding_boxes.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
