//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.MicrowunderlandInterfaces
{
    [Serializable]
    public class ListNamed2DPositionsMsg : Message
    {
        public const string k_RosMessageName = "microwunderland_interfaces/ListNamed2DPositions";
        public override string RosMessageName => k_RosMessageName;

        public Named2DPositionMsg[] named_positions;

        public ListNamed2DPositionsMsg()
        {
            this.named_positions = new Named2DPositionMsg[0];
        }

        public ListNamed2DPositionsMsg(Named2DPositionMsg[] named_positions)
        {
            this.named_positions = named_positions;
        }

        public static ListNamed2DPositionsMsg Deserialize(MessageDeserializer deserializer) => new ListNamed2DPositionsMsg(deserializer);

        private ListNamed2DPositionsMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.named_positions, Named2DPositionMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.named_positions);
            serializer.Write(this.named_positions);
        }

        public override string ToString()
        {
            return "ListNamed2DPositionsMsg: " +
            "\nnamed_positions: " + System.String.Join(", ", named_positions.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
