//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.MicrowunderlandInterfaces
{
    [Serializable]
    public class Named2DPositionMsg : Message
    {
        public const string k_RosMessageName = "microwunderland_interfaces/Named2DPosition";
        public override string RosMessageName => k_RosMessageName;

        public double x;
        public double y;
        public string name;

        public Named2DPositionMsg()
        {
            this.x = 0.0;
            this.y = 0.0;
            this.name = "";
        }

        public Named2DPositionMsg(double x, double y, string name)
        {
            this.x = x;
            this.y = y;
            this.name = name;
        }

        public static Named2DPositionMsg Deserialize(MessageDeserializer deserializer) => new Named2DPositionMsg(deserializer);

        private Named2DPositionMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.x);
            deserializer.Read(out this.y);
            deserializer.Read(out this.name);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.x);
            serializer.Write(this.y);
            serializer.Write(this.name);
        }

        public override string ToString()
        {
            return "Named2DPositionMsg: " +
            "\nx: " + x.ToString() +
            "\ny: " + y.ToString() +
            "\nname: " + name.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
