//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.MicrowunderlandInterfaces
{
    [Serializable]
    public class Named2DPositionMsg : Message
    {
        public const string k_RosMessageName = "microwunderland_interfaces/Named2DPosition";
        public override string RosMessageName => k_RosMessageName;

        public Vector2DMsg position;
        public string name;

        public Named2DPositionMsg()
        {
            this.position = new Vector2DMsg();
            this.name = "";
        }

        public Named2DPositionMsg(Vector2DMsg position, string name)
        {
            this.position = position;
            this.name = name;
        }

        public static Named2DPositionMsg Deserialize(MessageDeserializer deserializer) => new Named2DPositionMsg(deserializer);

        private Named2DPositionMsg(MessageDeserializer deserializer)
        {
            this.position = Vector2DMsg.Deserialize(deserializer);
            deserializer.Read(out this.name);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.position);
            serializer.Write(this.name);
        }

        public override string ToString()
        {
            return "Named2DPositionMsg: " +
            "\nposition: " + position.ToString() +
            "\nname: " + name.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
