//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.MicrowunderlandInterfaces
{
    [Serializable]
    public class StringUint16PairMsg : Message
    {
        public const string k_RosMessageName = "microwunderland_interfaces/StringUint16Pair";
        public override string RosMessageName => k_RosMessageName;

        //  A key value pair composed form a string and a unsigned 16 bit integer
        public string key;
        public ushort value;

        public StringUint16PairMsg()
        {
            this.key = "";
            this.value = 0;
        }

        public StringUint16PairMsg(string key, ushort value)
        {
            this.key = key;
            this.value = value;
        }

        public static StringUint16PairMsg Deserialize(MessageDeserializer deserializer) => new StringUint16PairMsg(deserializer);

        private StringUint16PairMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.key);
            deserializer.Read(out this.value);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.key);
            serializer.Write(this.value);
        }

        public override string ToString()
        {
            return "StringUint16PairMsg: " +
            "\nkey: " + key.ToString() +
            "\nvalue: " + value.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
