//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.MicrowunderlandInterfaces
{
    [Serializable]
    public class TrackedObjectMsg : Message
    {
        public const string k_RosMessageName = "microwunderland_interfaces/TrackedObject";
        public override string RosMessageName => k_RosMessageName;

        public Vector2DMsg position;
        public Vector2DMsg velocity;
        public Vector2DMsg acceleration;
        public ushort id;
        public bool undetected;

        public TrackedObjectMsg()
        {
            this.position = new Vector2DMsg();
            this.velocity = new Vector2DMsg();
            this.acceleration = new Vector2DMsg();
            this.id = 0;
            this.undetected = false;
        }

        public TrackedObjectMsg(Vector2DMsg position, Vector2DMsg velocity, Vector2DMsg acceleration, ushort id, bool undetected)
        {
            this.position = position;
            this.velocity = velocity;
            this.acceleration = acceleration;
            this.id = id;
            this.undetected = undetected;
        }

        public static TrackedObjectMsg Deserialize(MessageDeserializer deserializer) => new TrackedObjectMsg(deserializer);

        private TrackedObjectMsg(MessageDeserializer deserializer)
        {
            this.position = Vector2DMsg.Deserialize(deserializer);
            this.velocity = Vector2DMsg.Deserialize(deserializer);
            this.acceleration = Vector2DMsg.Deserialize(deserializer);
            deserializer.Read(out this.id);
            deserializer.Read(out this.undetected);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.position);
            serializer.Write(this.velocity);
            serializer.Write(this.acceleration);
            serializer.Write(this.id);
            serializer.Write(this.undetected);
        }

        public override string ToString()
        {
            return "TrackedObjectMsg: " +
            "\nposition: " + position.ToString() +
            "\nvelocity: " + velocity.ToString() +
            "\nacceleration: " + acceleration.ToString() +
            "\nid: " + id.ToString() +
            "\nundetected: " + undetected.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
