//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.MicrowunderlandInterfaces
{
    [Serializable]
    public class TrackedObjectsMsg : Message
    {
        public const string k_RosMessageName = "microwunderland_interfaces/TrackedObjects";
        public override string RosMessageName => k_RosMessageName;

        public TrackedObjectMsg[] objects;

        public TrackedObjectsMsg()
        {
            this.objects = new TrackedObjectMsg[0];
        }

        public TrackedObjectsMsg(TrackedObjectMsg[] objects)
        {
            this.objects = objects;
        }

        public static TrackedObjectsMsg Deserialize(MessageDeserializer deserializer) => new TrackedObjectsMsg(deserializer);

        private TrackedObjectsMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.objects, TrackedObjectMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.objects);
            serializer.Write(this.objects);
        }

        public override string ToString()
        {
            return "TrackedObjectsMsg: " +
            "\nobjects: " + System.String.Join(", ", objects.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
